sudo: required
services:
  - docker

before_install:
  - docker build -t mrscottiefy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mrscottiefy/docker-react npm run test

before_deploy: "echo '=== Ready to deploy!==='"

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-ap-southeast-1-370328880810"
  bucket_path: "docker"
  skip_cleanup: true
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"